# Terragon Autonomous SDLC Value Discovery Configuration
# Advanced Repository Configuration (88% maturity)
# Optimized for Quantum Computing Workloads

meta:
  version: "2.1.0"
  repository_name: "quantum-inspired-task-planner"
  repository_type: "quantum_optimization"
  maturity_level: "advanced"
  created_at: "2025-08-01T14:58:00Z"
  last_updated: "2025-08-01T14:58:00Z"
  maintainer: "Terragon Autonomous SDLC System"

# Scoring Configuration for Advanced Repositories
scoring:
  model_version: "hybrid_v2.1"
  
  # Advanced weighting for mature quantum computing repositories
  weights:
    wsjf: 0.35          # Weighted Shortest Job First
    ice: 0.25           # Impact, Confidence, Ease
    technical_debt: 0.25 # Technical debt and maintenance
    quantum_boost: 0.15  # Quantum computing specific adjustments
  
  # Advanced scoring thresholds
  thresholds:
    min_composite_score: 15.0    # Higher threshold for advanced repos
    max_risk_factor: 0.75        # Lower risk tolerance
    security_multiplier: 2.0     # Security priority boost
    compliance_multiplier: 1.8   # Compliance urgency boost
    performance_multiplier: 1.6  # Performance optimization boost
    quantum_multiplier: 1.5      # Quantum-specific task boost
  
  # Quantum Computing Domain Boosts
  quantum_domain_boosts:
    qubo_optimization: 1.5       # QUBO formulation improvements
    quantum_backend: 1.4         # Backend integration enhancements  
    hybrid_algorithms: 1.3       # Classical-quantum hybrid improvements
    quantum_security: 1.6        # Quantum cryptography and security
    error_mitigation: 1.4        # Quantum error correction/mitigation
    quantum_machine_learning: 1.3 # QML applications
    quantum_networking: 1.2      # Quantum communication protocols
  
  # Learning and adaptation parameters
  learning:
    enabled: true
    learning_rate: 0.1
    confidence_decay: 0.95
    outcome_weight: 0.3
    prediction_history_limit: 100

# Value Discovery Sources - Comprehensive for Advanced Repos
discovery:
  sources:
    git_history:
      enabled: true
      analysis_depth: 500        # Deeper analysis for advanced repos
      patterns:
        - "TODO"
        - "FIXME"
        - "HACK"
        - "XXX"
        - "DEPRECATED"
        - "QUANTUM_TODO"         # Quantum-specific markers
        - "PERFORMANCE_ISSUE"
        - "SECURITY_REVIEW"
      commit_message_keywords:
        - "quick fix"
        - "temporary"
        - "workaround"
        - "refactor needed"
        - "optimize"
        - "quantum backend"
        - "performance"
    
    static_analysis:
      enabled: true
      tools:
        python:
          - ruff
          - mypy  
          - bandit
          - safety
          - vulture     # Dead code detection
          - radon       # Complexity analysis
          - prospector  # Comprehensive analysis
        security:
          - semgrep
          - codeql
          - snyk
          - trivy
        quantum_specific:
          - qiskit_lint       # Quantum circuit optimization
          - quantum_security  # Quantum crypto analysis
          - qubo_validator    # QUBO formulation validation
    
    issue_trackers:
      enabled: true
      github:
        include_discussions: true
        label_priority_map:
          "critical": 10
          "high": 8
          "quantum": 9
          "performance": 7
          "security": 9
          "technical-debt": 6
    
    vulnerability_databases:
      enabled: true
      sources:
        - nvd
        - osv
        - github_advisory
        - quantum_security_db  # Quantum-specific vulnerabilities
      auto_prioritize_critical: true
    
    performance_monitoring:
      enabled: true
      metrics:
        - execution_time
        - memory_usage
        - quantum_gate_count    # Quantum-specific metrics
        - qubit_utilization
        - quantum_error_rate
        - classical_fallback_rate
      regression_threshold: 0.05  # 5% performance regression trigger
    
    research_integration:
      enabled: true
      sources:
        - arxiv_quantum_cs
        - quantum_computing_journals
        - quantum_algorithm_updates
        - hardware_announcements
      update_frequency: "weekly"

# Execution Framework for Advanced Repositories
execution:
  strategy: "intelligent_autonomous"
  
  concurrency:
    max_concurrent_tasks: 2      # Conservative for advanced repos
    task_isolation: true
    resource_limits:
      cpu_percent: 80
      memory_gb: 8
      quantum_credits: 100       # Quantum computing resource limits
  
  quality_gates:
    pre_execution:
      - syntax_validation
      - dependency_check
      - security_scan
      - quantum_compatibility    # Quantum-specific validation
    
    post_execution:
      - unit_tests
      - integration_tests
      - performance_tests
      - security_regression
      - quantum_simulation      # Quantum algorithm validation
    
    quality_thresholds:
      test_coverage_min: 85
      security_score_min: 90
      performance_regression_max: 5
      complexity_increase_max: 10
      quantum_fidelity_min: 0.95  # Quantum accuracy threshold
  
  rollback_triggers:
    - test_failure
    - security_violation
    - performance_regression
    - quantum_error_spike      # Quantum-specific rollback
    - compliance_violation
    - dependency_conflicts
  
  approval_workflows:
    security_changes:
      approvers: ["security-team", "maintainer"]
      auto_approve_threshold: 70
    
    architecture_changes:
      approvers: ["tech-lead", "architect"]
      auto_approve_threshold: 60
    
    quantum_algorithms:
      approvers: ["quantum-expert", "research-team"]
      auto_approve_threshold: 50
    
    performance_critical:
      approvers: ["performance-team"]
      auto_approve_threshold: 75

# Advanced Task Categories for Quantum Computing
task_categories:
  quantum_optimization:
    description: "QUBO formulation and quantum algorithm improvements"
    base_priority: 8
    effort_multiplier: 1.2
    confidence_factor: 0.8
    
  backend_integration:
    description: "Quantum backend connectivity and optimization"
    base_priority: 7
    effort_multiplier: 1.4
    confidence_factor: 0.7
    
  hybrid_algorithms:
    description: "Classical-quantum hybrid computation improvements"
    base_priority: 7
    effort_multiplier: 1.3
    confidence_factor: 0.75
    
  quantum_security:
    description: "Quantum cryptography and security enhancements"
    base_priority: 9
    effort_multiplier: 1.5
    confidence_factor: 0.65
    
  performance_optimization:
    description: "Computational performance and efficiency improvements"
    base_priority: 6
    effort_multiplier: 1.1
    confidence_factor: 0.85
    
  technical_debt:
    description: "Code quality, maintainability, and refactoring"
    base_priority: 5
    effort_multiplier: 1.0
    confidence_factor: 0.9
    
  research_integration:
    description: "Latest quantum computing research integration"
    base_priority: 4
    effort_multiplier: 2.0
    confidence_factor: 0.5
    
  documentation:
    description: "Documentation improvements and updates"
    base_priority: 3
    effort_multiplier: 0.8
    confidence_factor: 0.95

# Metrics and Tracking Configuration
metrics:
  collection_interval: "hourly"
  retention_period: "1 year"
  
  business_metrics:
    - development_velocity
    - defect_reduction_rate
    - security_incident_count
    - performance_improvement_percent
    - quantum_accuracy_improvement
    - research_integration_count
    - community_contribution_rate
  
  technical_metrics:
    - code_quality_score
    - test_coverage_percent
    - dependency_freshness
    - security_vulnerability_count
    - performance_regression_count
    - quantum_gate_efficiency
    - classical_fallback_rate
    - qubit_utilization_efficiency
  
  value_metrics:
    - tasks_discovered_count
    - tasks_completed_count
    - total_value_delivered
    - average_completion_time
    - prediction_accuracy
    - roi_measurement
    - cost_savings_achieved
    - quantum_performance_gains

# Reporting and Analytics
reporting:
  frequency: "daily"
  formats: ["json", "markdown", "html"]
  
  dashboard_sections:
    - executive_summary
    - value_discovery_trends
    - quantum_performance_metrics
    - security_posture
    - research_integration_status
    - technical_debt_evolution
    - prediction_accuracy_tracking
  
  alerts:
    critical_security: "immediate"
    performance_regression: "immediate"  
    quantum_error_spike: "immediate"
    high_value_opportunity: "hourly"
    prediction_accuracy_drop: "daily"

# Integration Configuration
integrations:
  github:
    enabled: true
    auto_create_issues: true
    auto_create_prs: false       # Conservative for advanced repos
    pr_template: ".terragon/templates/pr_template.md"
    issue_template: ".terragon/templates/issue_template.md"
  
  quantum_backends:
    dwave:
      enabled: true
      monitoring: true
      cost_tracking: true
    ibm_quantum:
      enabled: true
      monitoring: true
      cost_tracking: true
    azure_quantum:
      enabled: true
      monitoring: true
      cost_tracking: true
    
  monitoring_tools:
    prometheus:
      enabled: true
      quantum_metrics: true
    grafana:
      enabled: true
      quantum_dashboards: true
    
  notification_channels:
    slack:
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channels:
        critical: "#quantum-critical"
        high: "#quantum-dev"
        medium: "#quantum-updates"
    
    email:
      smtp_config: "${EMAIL_CONFIG}"
      recipients:
        critical: ["team-lead@company.com", "security@company.com"]
        high: ["dev-team@company.com"]

# Advanced Security Configuration
security:
  vulnerability_scanning:
    frequency: "continuous"
    include_quantum_specific: true
    auto_fix_threshold: 7.0      # CVSS score threshold
  
  secret_detection:
    quantum_api_keys: true
    cloud_quantum_tokens: true
    quantum_credentials: true
    
  compliance_frameworks:
    - SOC2
    - GDPR
    - NIST
    - quantum_security_standards
  
  quantum_security_policies:
    quantum_key_rotation: "30 days"
    quantum_session_timeout: "1 hour"
    quantum_audit_trail: true
    quantum_access_logging: true

# Research and Innovation Pipeline
research:
  algorithm_monitoring:
    arxiv_categories:
      - "quant-ph"
      - "cs.ET"
      - "cs.CC"
    
    keyword_tracking:
      - "QAOA"
      - "VQE"
      - "quantum approximate optimization"
      - "quantum machine learning"
      - "quantum advantage"
      - "NISQ algorithms"
  
  benchmark_tracking:
    quantum_supremacy_claims: true
    algorithm_improvements: true
    hardware_announcements: true
    
  innovation_pipeline:
    idea_generation: "automated"
    feasibility_analysis: "ai_assisted"
    impact_assessment: "quantified"
    implementation_roadmap: "generated"

# Cost Optimization
cost_optimization:
  quantum_resource_management:
    auto_scaling: true
    cost_threshold_alerts: true
    usage_optimization: true
    
  classical_fallback_strategy:
    cost_based_switching: true
    performance_threshold: 0.85
    accuracy_threshold: 0.95
    
  budget_management:
    monthly_quantum_budget: 1000  # USD
    cost_tracking_granularity: "per_job"
    optimization_recommendations: true

# Continuous Learning Configuration
learning:
  model_updates:
    frequency: "weekly"
    validation_method: "cross_validation"
    performance_tracking: true
    
  feedback_loops:
    outcome_tracking: true
    user_feedback_integration: true
    performance_correlation: true
    
  knowledge_base:
    quantum_patterns: true
    optimization_strategies: true
    failure_modes: true
    best_practices: true

# Environment-Specific Configuration
environments:
  development:
    quantum_simulation_only: true
    cost_limits: 10               # USD per day
    auto_execution: true
    
  staging:
    real_quantum_backends: true
    cost_limits: 100             # USD per day  
    auto_execution: false        # Manual approval required
    
  production:
    real_quantum_backends: true
    cost_limits: 500             # USD per day
    auto_execution: false        # Manual approval required
    monitoring_enhanced: true