# Terragon Autonomous SDLC Value Discovery Configuration
# Advanced Quantum Computing Repository - Enterprise Grade

version: "2.0"
repository:
  name: "quantum-inspired-task-planner"
  type: "quantum-computing-library"
  maturity_level: "advanced"  # 88% maturity
  domain: "quantum-optimization"
  frameworks: ["quantum-computing", "task-scheduling", "optimization"]

# Value Discovery Engine Configuration
discovery:
  # Continuous monitoring intervals (minutes)
  scan_interval: 60
  deep_analysis_interval: 1440  # 24 hours
  
  # Multi-source signal harvesting
  signal_sources:
    git_history:
      enabled: true
      lookback_days: 180
      branch_patterns: ["main", "develop", "feature/*", "hotfix/*"]
      analyze_commit_patterns: true
      detect_hotspots: true
      
    static_analysis:
      enabled: true
      tools:
        - ruff          # Python linting and code quality
        - mypy          # Type checking
        - bandit        # Security scanning
        - safety        # Dependency vulnerability scanning
        - semgrep       # SAST security analysis
        - quantum_linter # Custom quantum code analysis
      quantum_specific:
        - qubo_optimization_patterns
        - quantum_backend_usage
        - classical_fallback_detection
        - performance_bottlenecks
        
    dependency_analysis:
      enabled: true
      scan_outdated: true
      security_vulnerabilities: true
      license_compliance: true
      quantum_dependencies:
        - "dwave-ocean-sdk"
        - "azure-quantum"
        - "qiskit"
        - "qiskit-optimization"
      
    issue_tracking:
      enabled: true
      sources: ["github_issues", "github_discussions"]
      sentiment_analysis: true
      priority_detection: true
      
    performance_monitoring:
      enabled: true
      metrics:
        - quantum_solver_performance
        - classical_fallback_usage
        - memory_consumption
        - benchmark_trends
      baseline_comparison: true
      regression_detection: true

# Advanced Prioritization System
prioritization:
  # Hybrid scoring model weights
  scoring_weights:
    wsjf: 0.35          # Weighted Shortest Job First
    ice: 0.25           # Impact, Confidence, Ease
    technical_debt: 0.25 # Technical debt severity
    quantum_boost: 0.15  # Quantum computing specific boost
  
  # WSJF Components
  wsjf_factors:
    user_business_value: 0.3
    time_criticality: 0.3
    risk_reduction: 0.2
    job_size: 0.2
  
  # ICE Components  
  ice_factors:
    impact: 0.4      # Business/technical impact
    confidence: 0.3  # Confidence in estimate
    ease: 0.3        # Implementation ease
  
  # Technical Debt Factors
  technical_debt_factors:
    code_complexity: 0.25
    security_vulnerabilities: 0.30
    performance_issues: 0.20
    maintainability: 0.15
    test_coverage: 0.10
  
  # Quantum-specific priority boosts
  quantum_priority_boosts:
    quantum_performance_optimization: 1.5
    quantum_security_improvements: 1.4
    quantum_backend_modernization: 1.3
    hybrid_algorithm_optimization: 1.2
    quantum_cost_optimization: 1.2

# Task Categories with Adaptive Scoring
task_categories:
  security:
    base_priority: 9
    urgency_multiplier: 1.5
    quantum_considerations:
      - quantum_credential_protection
      - quantum_communication_security
      - post_quantum_cryptography_readiness
      
  performance:
    base_priority: 7
    urgency_multiplier: 1.2
    quantum_considerations:
      - quantum_vs_classical_performance
      - qubo_formulation_efficiency
      - quantum_backend_optimization
      - hybrid_algorithm_tuning
      
  maintenance:
    base_priority: 5
    urgency_multiplier: 1.0
    quantum_considerations:
      - quantum_dependency_updates
      - quantum_sdk_migrations
      - deprecated_quantum_api_updates
      
  innovation:
    base_priority: 6
    urgency_multiplier: 0.9
    quantum_considerations:
      - new_quantum_algorithms
      - emerging_quantum_hardware
      - quantum_research_integration
      - community_contributions

# Autonomous Execution Framework
execution:
  # Task execution protocols
  auto_execution:
    enabled: true
    max_concurrent_tasks: 3
    require_approval_for:
      - security_changes
      - breaking_changes
      - quantum_backend_modifications
      - performance_critical_changes
    
  # Risk management
  risk_assessment:
    enabled: true
    risk_thresholds:
      low: 0.3
      medium: 0.6
      high: 0.8
    quantum_risk_factors:
      - quantum_backend_availability
      - quantum_cost_implications
      - classical_fallback_impact
      - algorithm_complexity_changes
  
  # Rollback capabilities
  rollback:
    enabled: true
    auto_rollback_conditions:
      - test_failures
      - performance_regression > 20%
      - quantum_solver_failures
      - security_scan_failures
    backup_retention_days: 30
  
  # PR generation
  pull_requests:
    auto_create: true
    templates:
      security: ".github/PULL_REQUEST_TEMPLATE/security.md"
      performance: ".github/PULL_REQUEST_TEMPLATE/performance.md"
      quantum: ".github/PULL_REQUEST_TEMPLATE/quantum.md"
    require_review:
      - security_expert
      - quantum_computing_expert
      - performance_engineer

# Perpetual Learning System
learning:
  # Outcome tracking
  outcome_tracking:
    enabled: true
    metrics:
      - task_completion_rate
      - value_delivered
      - time_to_completion
      - regression_incidents
      - quantum_performance_improvements
  
  # Model refinement
  model_refinement:
    enabled: true
    refinement_interval_days: 30
    learning_rate: 0.1
    feedback_sources:
      - execution_outcomes
      - user_feedback
      - performance_metrics
      - quantum_benchmark_results
  
  # Pattern recognition
  pattern_recognition:
    enabled: true
    quantum_patterns:
      - optimal_qubo_formulations
      - efficient_quantum_backend_selection
      - performance_optimization_patterns
      - common_quantum_development_issues
  
  # Knowledge base
  knowledge_base:
    path: ".terragon/knowledge/"
    auto_update: true
    retention_policy: "keep_successful_patterns"
    quantum_expertise:
      - quantum_algorithm_library
      - backend_performance_profiles
      - optimization_best_practices
      - troubleshooting_guides

# Advanced Repository Intelligence
repository_intelligence:
  # Code analysis patterns
  code_patterns:
    quantum_optimization:
      - qubo_matrix_construction
      - quantum_annealing_parameters
      - hybrid_classical_quantum_workflows
      - backend_abstraction_patterns
    
    performance_critical:
      - solver_performance_bottlenecks
      - memory_optimization_opportunities
      - parallel_processing_potential
      - caching_strategies
    
    security_sensitive:
      - quantum_credential_handling
      - api_key_management
      - secure_quantum_communication
      - post_quantum_cryptography
  
  # Architectural analysis
  architecture:
    quantum_backend_abstraction: "excellent"
    pluggable_solver_system: "excellent"
    classical_fallback_design: "good"
    performance_monitoring: "good"
    security_architecture: "excellent"
  
  # Quality metrics
  quality_gates:
    test_coverage_threshold: 80
    security_scan_threshold: "high"
    performance_regression_threshold: 15
    quantum_solver_success_rate: 95

# Integration Configuration
integrations:
  github:
    enabled: true
    features:
      - issues
      - pull_requests
      - discussions
      - security_advisories
      - dependabot
  
  quantum_backends:
    dwave:
      enabled: false  # Requires credentials
      cost_monitoring: true
    ibm_quantum:
      enabled: false  # Requires credentials
      queue_monitoring: true
    azure_quantum:
      enabled: false  # Requires credentials
      service_monitoring: true
  
  monitoring:
    prometheus:
      enabled: false  # Optional
      metrics_port: 9090
    grafana:
      enabled: false  # Optional
      dashboard_path: "monitoring/grafana_dashboard.json"

# Notification and Reporting
notifications:
  channels:
    slack:
      enabled: false  # Configure webhook
      high_priority_channel: "#quantum-alerts"
      general_channel: "#quantum-development"
    
    email:
      enabled: false  # Configure SMTP
      recipients:
        - "quantum-team@company.com"
        - "devops@company.com"
  
  reporting:
    daily_summary: true
    weekly_deep_dive: true
    monthly_trends: true
    quantum_performance_reports: true

# Advanced Customization
customization:
  # Domain-specific rules
  quantum_computing_rules:
    - name: "QUBO Optimization Detection"
      pattern: "qubo|QUBO|quadratic.*unconstrained"
      priority_boost: 1.3
      category: "performance"
    
    - name: "Quantum Backend Integration"
      pattern: "dwave|ibm.*quantum|azure.*quantum"
      priority_boost: 1.4
      category: "integration"
    
    - name: "Classical Fallback Optimization"
      pattern: "simulated.*annealing|genetic.*algorithm|tabu.*search"
      priority_boost: 1.2
      category: "performance"
  
  # Custom metrics
  custom_metrics:
    quantum_efficiency_ratio:
      description: "Ratio of quantum to classical performance"
      calculation: "quantum_solve_time / classical_solve_time"
      target: "< 0.5"  # Quantum should be faster
    
    backend_utilization:
      description: "Percentage of quantum backend usage vs classical"
      calculation: "quantum_runs / total_runs"
      target: "> 0.7"  # Prefer quantum when available
    
    cost_efficiency:
      description: "Cost per optimization solved"
      calculation: "quantum_backend_cost / problems_solved"
      target: "minimize"

# Development and Testing
development:
  # Local development support
  local_mode:
    enabled: true
    mock_quantum_backends: true
    simulated_delays: false
    debug_logging: true
  
  # Testing configuration
  testing:
    property_based_testing: true
    quantum_simulation_testing: true
    performance_benchmarking: true
    security_testing: true
  
  # Debugging aids
  debugging:
    quantum_solver_debugging: true
    qubo_matrix_visualization: true
    solution_analysis_tools: true
    performance_profiling: true

# Compliance and Governance
compliance:
  # Regulatory requirements
  regulations:
    - "GDPR"      # Data protection
    - "SOC2"      # Security compliance
    - "NIST"      # Cybersecurity framework
  
  # Audit trail
  audit:
    enabled: true
    retention_days: 365
    immutable_logs: true
    change_tracking: true
  
  # Policy enforcement
  policies:
    quantum_resource_usage:
      max_daily_cost: 100.0  # USD
      max_concurrent_jobs: 10
      require_approval_above: 50.0  # USD per job
    
    security_requirements:
      mandatory_security_scan: true
      vulnerability_fix_sla_days: 14
      quantum_credential_rotation_days: 90

# Metadata
metadata:
  created: "2025-08-01"
  version: "2.0.0"
  last_updated: "2025-08-01"
  schema_version: "terragon-v2"
  quantum_domain_version: "1.0"
  
  # Configuration fingerprint for change detection
  config_hash: "sha256:quantum-advanced-2025-08-01"
  
  # Quantum computing specific metadata
  quantum_metadata:
    supported_backends: ["simulator", "dwave", "ibm", "azure"]
    optimization_types: ["QUBO", "Ising", "QAOA"]
    classical_solvers: ["simulated_annealing", "genetic", "tabu_search"]
    hybrid_strategies: ["decomposition", "warm_start", "constraint_relaxation"]